services:
  api:
    container_name: lms-api-gateway-service
    build:
      context: .
      dockerfile: Dockerfile
    image: lms-mini/api-gateway:v1
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./logs:/app/logs
