server:
  http2:
    enabled: true
  port: 8080
  servlet:
    context-path: /
  shutdown: graceful

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus,metrics"
  endpoint:
    health:
      show-details: ALWAYS

config:
  service-name: lms-api-gateway-service
  api:
    authn: http://localhost:8081
    author: http://localhost:8082

spring:
  profiles:
    active: @active.mode@
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: ${config.service-name}
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false
      discovery:
        enabled: true
        instance-id: ${config.service-name}
        service-name: ${config.service-name}
        health-check-path: /actuator/health
        prefer-ip-address: true
        prefer-agent-address: false
        health-check-interval: 25s
        health-check-critical-timeout: 90s
        register: true
        deregister: true
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin RETAIN_UNIQUE
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-methods: "*"
                allowed-headers: "*"
                allow-credentials: false
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: lms-authn-continental-auth
              uri: lb://lms-authn-service
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/token, /api/v1/auth/login
                - RewritePath=/auth/refresh, /api/v1/auth/refresh-token
                - RewritePath=/auth/userinfo, /api/v1/auth/me
                - RewritePath=/auth/(?<path>.*), /api/v1/auth/$\{path}
            - id: lms-authn-continental-users
              uri: lb://lms-authn-service
              predicates:
                - Path=/users/**
              filters:
                - RewritePath=/users/(?<userId>.*)/summary, /internal/v1/AuthnUser/$\{userId}/info
            - id: lms-author-continental-permissions
              uri: lb://lms-author-service
              predicates:
                - Path=/admin/permissions,/admin/permissions/**
              filters:
                - RewritePath=/admin/permissions(?<path>/?.*), /api/v1/permissions$\{path}
            - id: lms-author-continental-staff-activity
              uri: lb://lms-author-service
              predicates:
                - Path=/staff-activity/**
            - id: lms-authn-service
              uri: lb://lms-authn-service
              predicates:
                - Path=/authn/**
              filters:
                - RewritePath=/authn/(?<path>.*), /$\{path}
            - id: lms-author-service
              uri: lb://lms-author-service
              predicates:
                - Path=/author/**
              filters:
                - RewritePath=/author/(?<path>.*), /$\{path}
  main:
    allow-bean-definition-overriding: true
  mvc:
    problemdetails:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  show-actuator: false
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urls-primary-name: "lms-api-gateway-service"
    urls:
      - name: lms-api-gateway-service
        url: /v3/api-docs
      - name: lms-authn-service
        url: /authn/v3/api-docs
      - name: lms-author-service
        url: /author/v3/api-docs
