server:
  port: 8080

internal:
  service-key: ${INTERNAL_SERVICE_KEY:}
  shutdown: graceful
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,metrics
  endpoint:
    health:
      show-details: always

config:
  service-name: lms-api-gateway-service
  api:
    authn: http://localhost:8081
    author: http://localhost:8082
    course: localhost:8083
    learning: localhost:8084
    quiz: localhost:8085
    notice: localhost:8086
    billing: localhost:8087
    chat: localhost:8089

spring:
  application:
    name: ${config.service-name}
  http:
    codecs:
      max-in-memory-size: 10MB
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false
      discovery:
        enabled: true
        instance-id: ${spring.application.name}-${server.port}
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        prefer-ip-address: true
        health-check-interval: 15s
        register: true
        deregister: true
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin RETAIN_UNIQUE
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: lms-authn-continental-auth-token
              uri: lb://lms-authn-service
              predicates:
                - Path=/auth/token
              filters:
                - SetPath=/api/v1/auth/login
            - id: lms-authn-continental-auth-refresh
              uri: lb://lms-authn-service
              predicates:
                - Path=/auth/refresh
              filters:
                - SetPath=/api/v1/auth/refresh-token
            - id: lms-authn-continental-auth-userinfo
              uri: lb://lms-authn-service
              predicates:
                - Path=/auth/userinfo
              filters:
                - SetPath=/api/v1/auth/me
            - id: lms-authn-continental-auth
              uri: lb://lms-authn-service
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<path>.*), /api/v1/auth/$\{path}
            - id: lms-authn-service-direct-auth
              uri: lb://lms-authn-service
              predicates:
                - Path=/api/v1/auth/**
            - id: lms-authn-continental-users
              uri: lb://lms-authn-service
              predicates:
                - Path=/users/**
              filters:
                - RewritePath=/users/(?<userId>.*)/summary, /internal/v1/AuthnUser/$\{userId}/info
            - id: lms-author-continental-permissions
              uri: lb://lms-author-service
              predicates:
                - Path=/admin/permissions,/admin/permissions/**
              filters:
                - RewritePath=/admin/permissions(?<path>/?.*), /api/v1/permissions$\{path}
            - id: lms-author-continental-staff-activity
              uri: lb://lms-author-service
              predicates:
                - Path=/staff-activity/**
            - id: lms-authn-service
              uri: lb://lms-authn-service
              predicates:
                - Path=/authn/**
              filters:
                - RewritePath=/authn/(?<path>.*), /$\{path}
            - id: lms-author-service
              uri: lb://lms-author-service
              predicates:
                - Path=/author/**
              filters:
                - RewritePath=/author/(?<path>.*), /$\{path}
            - id: lms-course-service
              uri: lb://lms-course-service
              predicates:
                - Path=/course/**
              filters:
                - RewritePath=/course/(?<path>.*), /$\{path}
            - id: lms-chat-websocket
              uri: lb:ws://lms-chat-service
              predicates:
                - Path=/chat/ws,/chat/ws/**
              filters:
                - RewritePath=/chat/(?<path>.*), /$\{path}
            - id: lms-chat-service
              uri: lb://lms-chat-service
              predicates:
                - Path=/chat/**
              filters:
                - RewritePath=/chat/(?<path>.*), /$\{path}
            - id: lms-learning-service
              uri: lb://lms-learning-service
              predicates:
                - Path=/learning/**
              filters:
                - RewritePath=/learning/(?<path>.*), /$\{path}
            - id: lms-quiz-service
              uri: lb://lms-quiz-service
              predicates:
                - Path=/quiz/**
              filters:
                - RewritePath=/quiz/(?<path>.*), /$\{path}
            - id: lms-notice-service
              uri: lb://lms-notice-service
              predicates:
                - Path=/notice/**
              filters:
                - RewritePath=/notice/(?<path>.*), /$\{path}
            - id: lms-billing-service
              uri: lb://lms-billing-service
              predicates:
                - Path=/billing/**
              filters:
                - RewritePath=/billing/(?<path>.*), /$\{path}
  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  show-actuator: false
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urls-primary-name: lms-api-gateway-service
    urls:
      - name: lms-api-gateway-service
        url: /v3/api-docs
      - name: lms-authn-service
        url: /authn/v3/api-docs
      - name: lms-author-service
        url: /author/v3/api-docs
      - name: lms-course-service
        url: /course/v3/api-docs
      - name: lms-learning-service
        url: /learning/v3/api-docs
      - name: lms-quiz-service
        url: /quiz/v3/api-docs
      - name: lms-notice-service
        url: /notice/v3/api-docs
      - name: lms-billing-service
        url: /billing/v3/api-docs
      - name: lms-chat-service
        url: /chat/v3/api-docs
