server:
  http2:
    enabled: true
  port: 8080
  servlet:
    context-path: /
  shutdown: graceful

spring:
  application:
    name: ${config.service-name}
  cloud:
    consul:
      enabled: true
      config:
        enabled: false
      discovery:
        enabled: true
        instance-id: ${KUBERNETES_POD_NAME}
        service-name: ${config.service-name}
        health-check-path: /actuator/health
        prefer-ip-address: true
        prefer-agent-address: false
        health-check-interval: 25s
        health-check-critical-timeout: 90s
        register: true
        deregister: true
      host: consul-server.consul.svc.cluster.local
      port: 8500

config:
  service-name: lms-api-gateway-service
  api:
    authn: http://lms-authn-service
    author: http://lms-author-service

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  show-actuator: false
  swagger-ui:
    urls:
      - name: lms-api-gateway-service
        url: /v3/api-docs
      - name: lms-authn-service
        url: /authn/v3/api-docs
      - name: lms-author-service
        url: /author/v3/api-docs
