services:
  api:
    container_name: lms-authn-service
    build:
      context: .
      dockerfile: Dockerfile
    image: lms-mini/authn-service:v1
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    volumes:
      - ./logs:/app/logs
