server:
  port: 8088
  shutdown: graceful

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics

spring:
  application:
    name: lms-invoice-service
  config:
    import: optional:classpath:application-base.yaml
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lms_invoice_service?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: root
    hikari:
      schema: lms_invoice_service
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false
      discovery:
        enabled: true
        instance-id: ${spring.application.name}-${server.port}
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        prefer-ip-address: true
        health-check-interval: 15s
        register: true
        deregister: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

config:
  service-name: lms-invoice-service
  api:
    white-list:
      - /api/v1/internal/invoices

internal:
  service-key: ${INTERNAL_SERVICE_KEY:lms-mini-internal-change-me}
